import { defineConfig } from 'vitest/config';

/**
 * jsdom 단위 테스트 설정.
 *
 * 새로 추가되는 단위 테스트와 jsdom으로 옮겨진 기존 테스트의 실행 환경이다.
 * happy-dom 전용 mock(`tests/setup/canvas-mock.ts`)은 로드하지 않는다.
 * jsdom과 `canvas` 패키지가 DOM/Canvas/Image API를 표준 동작에 가깝게 제공한다.
 *
 * include는 비워둔 상태로 시작한다. 일괄 마이그레이션은 하지 않는다.
 * 파일을 jsdom으로 옮길 때 아래 두 가지를 함께 적용한다.
 *   1. 이 파일의 `include` 배열에 해당 경로를 추가한다.
 *   2. `vitest.node.config.ts`의 `exclude` 배열에 같은 경로를 추가해 중복 실행을 피한다.
 *
 * 정책은 `tests/TESTING-GUIDE.md`의 "테스트 환경 정책"을 따른다.
 */
export default defineConfig({
  test: {
    environment: 'jsdom',
    // jsdom 기본값은 외부 리소스 로드를 막아 blob/data URL 이미지 로드가 hang된다.
    // 'usable'로 두면 canvas 패키지와 함께 Image element 로드가 동작한다.
    environmentOptions: {
      jsdom: {
        resources: 'usable',
      },
    },
    include: [
      'tests/jsdom-limits/**/*.test.ts',
      'tests/unit/processor/unsafe-process-image/export-contract.test.ts',
      'tests/unit/types/strict-svg-sanitizer-types.test.ts',
      'tests/unit/core/source-fetch-guards/defaults.test.ts',
      'tests/unit/utils/image-info/get-image-properties.test.ts',
      'tests/unit/base/canvas-pool-threshold.test.ts',
      'tests/unit/utils/svg-compatibility.test.ts',
      'tests/unit/utils/inspect-svg-source-fetch-failures.test.ts',
      'tests/unit/utils/prefix-svg-ids-leakage.test.ts',
      'tests/unit/core/source-fetch-guards/blob-url.test.ts',
      'tests/unit/core/source-fetch-guards/abort-signal.test.ts',
      'tests/unit/base/stepped-processor.test.ts',
      'tests/unit/filters/filter-init.test.ts',
      'tests/unit/utils/format-utils.test.ts',
      'tests/unit/utils/svg-detection.test.ts',
      'tests/unit/utils/svg-optimizer.test.ts',
      'tests/unit/filters/plugin-system-convenience.test.ts',
      'tests/unit/core/source-fetch-guards/timeout.test.ts',
      'tests/unit/svg-sanitizer/inspect-sanitization-failures.test.ts',
      'tests/unit/utils/image-inspection.test.ts',
      'tests/unit/utils/inspect-svg-leakage.test.ts',
      'tests/unit/core/source-fetch-guards/bytes-limit.test.ts',
      'tests/unit/utils/inspect-svg-findings.test.ts',
      'tests/unit/utils/inspect-svg-analysis.test.ts',
      'tests/unit/composition/position-types.test.ts',
      'tests/unit/core/source-fetch-guards/svg-url.test.ts',
      'tests/unit/utils/svg-dimensions.test.ts',
      'tests/unit/composition/watermark-text.test.ts',
      'tests/unit/utils/inspect-svg-source-leakage.test.ts',
      'tests/unit/filters/plugin-system-manager.test.ts',
      'tests/unit/svg-sanitizer/inspect-sanitization-leakage.test.ts',
      'tests/unit/utils/browser-capabilities/features-facade.test.ts',
      'tests/unit/core/performance-utils.test.ts',
      'tests/unit/utils/inspect-svg-source-fetch.test.ts',
      'tests/unit/core/source-fetch-guards/protocol.test.ts',
      'tests/unit/utils/browser-capabilities/ssr-safety.test.ts',
      'tests/unit/utils/browser-capabilities/detector.test.ts',
      'tests/unit/utils/prefix-svg-ids-reference-rewrite.test.ts',
      'tests/unit/utils/prefix-svg-ids-id-rewrite.test.ts',
      'tests/unit/core/resize-calculator.constraints.test.ts',
      'tests/unit/utils/inspect-svg-source-sniffing.test.ts',
      'tests/unit/utils/prefix-svg-ids-deopt.test.ts',
      'tests/unit/utils/svg-data-url-policy.test.ts',
      'tests/unit/svg-sanitizer/inspect-sanitization-embedded-images.test.ts',
      'tests/unit/core/performance-config.test.ts',
      'tests/unit/core/batch-resizer.test.ts',
      'tests/unit/filters/plugin-system-application.test.ts',
      'tests/unit/utils/svg-policy-utils.test.ts',
      'tests/unit/core/auto-memory-manager.test.ts',
      'tests/unit/utils/source-utils.test.ts',
      'tests/unit/utils/inspect-svg-parse-boundary.test.ts',
      'tests/unit/core/resize-calculator.integration.test.ts',
      'tests/unit/utils/data-url.test.ts',
      'tests/unit/svg-sanitizer/inspect-sanitization-stages.test.ts',
      'tests/unit/base/high-res-detector.test.ts',
      'tests/unit/utils/image-info/fetch-image-source-blob.test.ts',
      'tests/unit/core/svg-complexity-analyzer.test.ts',
      'tests/unit/filters/color-plugins.test.ts',
      'tests/unit/types/resize-config.test.ts',
      'tests/unit/filters/blur-plugins.test.ts',
      'tests/unit/core/resize-calculator.fit-modes.test.ts',
      'tests/unit/filters/effect-plugins.test.ts',
      'tests/unit/utils/inspect-svg.test.ts',
      'tests/unit/utils/prefix-svg-ids.test.ts',
      'tests/unit/utils/inspect-svg-source.test.ts',
      'tests/unit/svg-sanitizer/inspect-sanitization.test.ts',
      'tests/unit/processor/source-converter-timer.test.ts',
      'tests/unit/composition/watermark-convenience.test.ts',
      'tests/unit/composition/watermark-image.test.ts',
      'tests/unit/composition/watermark-simple.test.ts',
      'tests/unit/scripts/llm-txt-generator.test.ts',
      'tests/contract/contract-config-smoke.test.ts',
      'tests/contract/public-api-exports.test.ts',
      'tests/contract/package-manifest.test.ts',
      'tests/security/svg-inline-sanitization/input-boundaries.test.ts',
      'tests/security/svg-inline-sanitization/external-reference-blocking.test.ts',
      'tests/security/source-type-detection.test.ts',
      'tests/security/svg-css-escape-bypass.test.ts',
      'tests/security/strict-svg-sanitizer.test.ts',
      'tests/security/svg-remote-fetch/remote-svg-sanitization.test.ts',
      'tests/security/svg-sanitizer-core.test.ts',
      'tests/security/svg-remote-fetch/fail-closed.test.ts',
      'tests/unit/utils/converters-quality-canvas.test.ts',
      'tests/unit/utils/converters-file-canvas.test.ts',
      'tests/security/svg-size-limits-jsdom.test.ts',
      'tests/contract/runtime-contract.test.ts',
      'tests/integration/svg-quality-fix.test.ts',
    ],
    exclude: ['**/node_modules/**', '**/dist/**', 'tests/browser/**'],
    passWithNoTests: true,
    globals: true,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      include: ['src/**/*.ts'],
      exclude: ['src/**/*.d.ts', 'src/**/*.test.ts', 'src/**/*.spec.ts'],
    },
    testTimeout: 30000,
    hookTimeout: 10000,
    retry: 1,
    reporters: ['verbose'],
  },
});
