import { defineConfig } from 'vitest/config';

/**
 * Node.js/happy-dom 테스트 설정 (브라우저 없는 빠른 단위 테스트)
 *
 * 브라우저 전용 smoke test(tests/browser/**)는 수집하지 않는다.
 */
export default defineConfig({
  test: {
    environment: 'happy-dom',
    setupFiles: ['./tests/setup/canvas-mock.ts'],
    include: ['tests/**/*.test.ts'],
    exclude: [
      '**/node_modules/**',
      '**/dist/**',
      'tests/browser/**',
      // jsdom 전용 (vitest.jsdom.config.ts include와 동기화)
      'tests/jsdom-limits/**',
      'tests/unit/processor/unsafe-process-image/export-contract.test.ts',
      'tests/unit/types/strict-svg-sanitizer-types.test.ts',
      'tests/unit/core/source-fetch-guards/defaults.test.ts',
      'tests/unit/utils/image-info/get-image-properties.test.ts',
      'tests/unit/base/canvas-pool-threshold.test.ts',
      'tests/unit/utils/svg-compatibility.test.ts',
      'tests/unit/utils/inspect-svg-source-fetch-failures.test.ts',
      'tests/unit/utils/prefix-svg-ids-leakage.test.ts',
      'tests/unit/core/source-fetch-guards/blob-url.test.ts',
      'tests/unit/core/source-fetch-guards/abort-signal.test.ts',
      'tests/unit/base/stepped-processor.test.ts',
      'tests/unit/filters/filter-init.test.ts',
      'tests/unit/utils/format-utils.test.ts',
      'tests/unit/utils/svg-detection.test.ts',
      'tests/unit/utils/svg-optimizer.test.ts',
      'tests/unit/filters/plugin-system-convenience.test.ts',
      'tests/unit/core/source-fetch-guards/timeout.test.ts',
      'tests/unit/svg-sanitizer/inspect-sanitization-failures.test.ts',
      'tests/unit/utils/image-inspection.test.ts',
      'tests/unit/utils/inspect-svg-leakage.test.ts',
      'tests/unit/core/source-fetch-guards/bytes-limit.test.ts',
      'tests/unit/utils/inspect-svg-findings.test.ts',
      'tests/unit/utils/inspect-svg-analysis.test.ts',
      'tests/unit/composition/position-types.test.ts',
      'tests/unit/core/source-fetch-guards/svg-url.test.ts',
      'tests/unit/utils/svg-dimensions.test.ts',
      'tests/unit/composition/watermark-text.test.ts',
      'tests/unit/utils/inspect-svg-source-leakage.test.ts',
      'tests/unit/filters/plugin-system-manager.test.ts',
      'tests/unit/svg-sanitizer/inspect-sanitization-leakage.test.ts',
      'tests/unit/utils/browser-capabilities/features-facade.test.ts',
      'tests/unit/core/performance-utils.test.ts',
      'tests/unit/utils/inspect-svg-source-fetch.test.ts',
      'tests/unit/core/source-fetch-guards/protocol.test.ts',
      'tests/unit/utils/browser-capabilities/ssr-safety.test.ts',
      'tests/unit/utils/browser-capabilities/detector.test.ts',
      'tests/unit/utils/prefix-svg-ids-reference-rewrite.test.ts',
      'tests/unit/utils/prefix-svg-ids-id-rewrite.test.ts',
      'tests/unit/core/resize-calculator.constraints.test.ts',
      'tests/unit/utils/inspect-svg-source-sniffing.test.ts',
      'tests/unit/utils/prefix-svg-ids-deopt.test.ts',
      'tests/unit/utils/svg-data-url-policy.test.ts',
      'tests/unit/svg-sanitizer/inspect-sanitization-embedded-images.test.ts',
      'tests/unit/core/performance-config.test.ts',
      'tests/unit/core/batch-resizer.test.ts',
      'tests/unit/filters/plugin-system-application.test.ts',
      'tests/unit/utils/svg-policy-utils.test.ts',
      'tests/unit/core/auto-memory-manager.test.ts',
      'tests/unit/utils/source-utils.test.ts',
      'tests/unit/utils/inspect-svg-parse-boundary.test.ts',
      'tests/unit/core/resize-calculator.integration.test.ts',
      'tests/unit/utils/data-url.test.ts',
      'tests/unit/svg-sanitizer/inspect-sanitization-stages.test.ts',
      'tests/unit/base/high-res-detector.test.ts',
      'tests/unit/utils/image-info/fetch-image-source-blob.test.ts',
      'tests/unit/core/svg-complexity-analyzer.test.ts',
      'tests/unit/filters/color-plugins.test.ts',
      'tests/unit/types/resize-config.test.ts',
      'tests/unit/filters/blur-plugins.test.ts',
      'tests/unit/core/resize-calculator.fit-modes.test.ts',
      'tests/unit/filters/effect-plugins.test.ts',
      'tests/unit/utils/inspect-svg.test.ts',
      'tests/unit/utils/prefix-svg-ids.test.ts',
      'tests/unit/utils/inspect-svg-source.test.ts',
      'tests/unit/svg-sanitizer/inspect-sanitization.test.ts',
      'tests/unit/processor/source-converter-timer.test.ts',
      'tests/unit/composition/watermark-convenience.test.ts',
      'tests/unit/composition/watermark-image.test.ts',
      'tests/unit/composition/watermark-simple.test.ts',
      'tests/unit/scripts/llm-txt-generator.test.ts',
      'tests/contract/contract-config-smoke.test.ts',
      'tests/contract/public-api-exports.test.ts',
      'tests/contract/package-manifest.test.ts',
      'tests/security/svg-inline-sanitization/input-boundaries.test.ts',
      'tests/security/svg-inline-sanitization/external-reference-blocking.test.ts',
      'tests/security/svg-remote-fetch/remote-svg-sanitization.test.ts',
      'tests/security/source-type-detection.test.ts',
      'tests/security/svg-css-escape-bypass.test.ts',
      'tests/security/strict-svg-sanitizer.test.ts',
      'tests/security/svg-sanitizer-core.test.ts',
      'tests/security/svg-remote-fetch/fail-closed.test.ts',
      'tests/unit/utils/converters-quality-canvas.test.ts',
      'tests/unit/utils/converters-file-canvas.test.ts',
      'tests/security/svg-size-limits-jsdom.test.ts',
      'tests/contract/runtime-contract.test.ts',
      'tests/integration/svg-quality-fix.test.ts',
      'tests/unit/core/onehot-renderer.test.ts',
      'tests/unit/core/resize-calculator.padding.test.ts',
      'tests/unit/processor/to-array-buffer-error.test.ts',
      'tests/unit/processor/to-element-cleanup.test.ts',
      'tests/unit/processor/typed-processor-simple.test.ts',
      'tests/unit/utils/image-info/fetch-image-format.test.ts',
      'tests/unit/utils/image-info/get-image-format.test.ts',
      'tests/unit/utils/image-loader.test.ts',
      'tests/unit/utils/image-info/get-image-info-jsdom.test.ts',
      'tests/unit/processor/format-cache-jsdom.test.ts',
      'tests/unit/utils/image-info/get-image-dimensions-jsdom.test.ts',
      'tests/unit/processor/unsafe-process-image/error-handling-jsdom.test.ts',
      'tests/unit/processor/typed-processor-jsdom.test.ts',
      'tests/unit/core/canvas-pool-integration-jsdom.test.ts',
      'tests/unit/core/lazy-render-pipeline-jsdom.test.ts',
      'tests/unit/core/advanced-filter-initialization-jsdom.test.ts',
      'tests/unit/scripts/llm-txt-generator.test.ts',
      'tests/unit/processor/processor-resize/chaining-jsdom.test.ts',
      'tests/unit/processor/processor-resize/multiple-resize-guard-jsdom.test.ts',
      'tests/unit/processor/processor-resize/output-formats-jsdom.test.ts',
      'tests/unit/processor/processor-resize/fit-modes-jsdom.test.ts',
      'tests/unit/presets/presets-jsdom.test.ts',
      'tests/unit/processor/image-loading-regression-jsdom.test.ts',
      'tests/security/svg-inline-sanitization/inline-rendering-jsdom.test.ts',
      'tests/unit/composition/image-composer.test.ts',
    ],
    globals: true,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      include: ['src/**/*.ts'],
      exclude: ['src/**/*.d.ts', 'src/**/*.test.ts', 'src/**/*.spec.ts'],
    },
    testTimeout: 30000,
    hookTimeout: 10000,
    retry: 1,
    reporters: ['verbose'],
  },
});
