import { describe, expect, it } from 'vitest';

import { isInlineSvg as isInlineSvgFromRoot } from '../../../src';
import { isInlineSvg } from '../../../src/utils';

describe('isInlineSvg', () => {
  it('순수 SVG 문자열을 인라인 SVG로 판정한다', () => {
    expect(isInlineSvg('<svg xmlns="http://www.w3.org/2000/svg"></svg>')).toBe(true);
  });

  it('자가 닫힘 SVG 루트도 인라인 SVG로 판정한다', () => {
    expect(isInlineSvg('<svg/>')).toBe(true);
  });

  it('BOM, XML 선언, 주석, DOCTYPE 뒤의 SVG 루트를 인라인 SVG로 판정한다', () => {
    const source = [
      '\uFEFF<?xml version="1.0" encoding="UTF-8"?>',
      '<!-- generated by editor -->',
      '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "">',
      '<svg xmlns="http://www.w3.org/2000/svg"></svg>',
    ].join('\n');

    expect(isInlineSvg(source)).toBe(true);
  });

  it('DOCTYPE internal subset 안의 > 문자를 선언 종료로 오해하지 않는다', () => {
    const source = [
      '<!DOCTYPE svg [',
      '<!ENTITY label "1 > 0">',
      ']>',
      '<svg xmlns="http://www.w3.org/2000/svg"></svg>',
    ].join('\n');

    expect(isInlineSvg(source)).toBe(true);
  });

  it('닫히지 않은 DOCTYPE 뒤의 SVG 문자열은 인라인 SVG로 판정하지 않는다', () => {
    const source = [
      '<!DOCTYPE svg [',
      '<!ENTITY label "1 > 0">',
      '<svg xmlns="http://www.w3.org/2000/svg"></svg>',
    ].join('\n');

    expect(isInlineSvg(source)).toBe(false);
  });

  it('HTML 조각 내부에 중첩된 SVG는 인라인 SVG로 판정하지 않는다', () => {
    expect(isInlineSvg('<div><svg></svg></div>')).toBe(false);
  });

  it('일반 HTML과 script 문자열은 인라인 SVG로 판정하지 않는다', () => {
    expect(isInlineSvg('<script>alert(1)</script>')).toBe(false);
    expect(isInlineSvg('<html><body><svg></svg></body></html>')).toBe(false);
  });

  it('빈 문자열과 공백 문자열은 인라인 SVG로 판정하지 않는다', () => {
    expect(isInlineSvg('')).toBe(false);
    expect(isInlineSvg('   \n\t')).toBe(false);
  });

  it('SVG Data URL은 인라인 SVG XML 문자열로 판정하지 않는다', () => {
    expect(isInlineSvg('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg"></svg>')).toBe(false);
  });

  it('루트 엔트리에서도 동일한 공개 유틸을 재노출한다', () => {
    expect(isInlineSvgFromRoot('<svg viewBox="0 0 1 1" />')).toBe(true);
  });
});
